Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IndentationStyle:
  Enabled: false
convention:Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false