default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marketplace_development
  password: postgres
  username: postgres
  host: localhost

test:
  <<: *default
  database: marketplace_test
  password: postgres
  username: postgres
  host: localhost
